"""Inject content between BEGIN_AGENT_TOOLKIT / END_AGENT_TOOLKIT markers."""
from __future__ import annotations

BEGIN_TEMPLATE = "<!-- BEGIN_AGENT_TOOLKIT:{region} — DO NOT EDIT — regenerated by `agent-toolkit fix` -->"
END_TEMPLATE = "<!-- END_AGENT_TOOLKIT:{region} -->"


def inject_region(source: str, region: str, body: str) -> str:
    begin_prefix = f"<!-- BEGIN_AGENT_TOOLKIT:{region}"
    end_marker = END_TEMPLATE.format(region=region)
    begin_idx = source.find(begin_prefix)
    if begin_idx == -1:
        raise ValueError(f"missing BEGIN marker for region {region!r}")
    begin_line_end = source.find("\n", begin_idx)
    if begin_line_end == -1:
        raise ValueError(f"malformed BEGIN marker for region {region!r}")
    end_idx = source.find(end_marker, begin_line_end)
    if end_idx == -1:
        raise ValueError(f"missing END marker for region {region!r}")
    if not body.endswith("\n"):
        body = body + "\n"
    new_block = (
        BEGIN_TEMPLATE.format(region=region)
        + "\n\n"
        + body
        + "\n"
        + end_marker
    )
    return source[:begin_idx] + new_block + source[end_idx + len(end_marker):]
